name: Publish Docker image
on:
  push:
  schedule:
    - cron: '40 17 * * 0'
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [main]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/anyakichi/dpdk-builder
          tags: ${{ matrix.tag }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: dpdk_rev=${{ matrix.tag  }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
