name: Publish Docker image
on:
  push:
  schedule:
    - cron: "40 17 * * 0"
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu: [latest, jammy, focal]
    steps:
      - run: |
          if [[ "${{ matrix.ubuntu }}" == latest ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.ref_name }}-${{ matrix.ubuntu }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/anyakichi/dpdk-builder
          tags: ${{ env.TAG }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            ubuntu_version=${{ matrix.ubuntu }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
