name: Publish Docker image
on:
  push:
  schedule:
    - cron: "40 17 * * 0"
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
          [
            "debian",
            "debian:bookworm",
            "ubuntu",
            "ubuntu:noble",
            "ubuntu:jammy",
            "ubuntu:focal",
          ]
    steps:
      - run: |
          BASE="${{ matrix.base }}"
          TAG="${{ github.ref_name }}-${BASE#*:}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAGS<<EOF" >> $GITHUB_ENV
          if [[ $BASE == debian ]]; then
            echo "${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          echo "$TAG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "TAGS_CROSS<<EOF" >> $GITHUB_ENV
          if [[ $BASE == debian ]]; then
            echo "${{ github.ref_name }}-cross" >> $GITHUB_ENV
          fi
          echo "$TAG-cross" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/anyakichi/dpdk-builder
          tags: ${{ env.TAGS }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          build-args: |
            base=${{ matrix.base }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/metadata-action@v5
        id: meta_cross
        with:
          images: ghcr.io/anyakichi/dpdk-builder
          tags: ${{ env.TAGS_CROSS }}
      - uses: docker/build-push-action@v5
        with:
          context: cross
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          build-args: |
            base=ghcr.io/anyakichi/dpdk-builder:${{ env.TAG }}
          tags: ${{ steps.meta_cross.outputs.tags }}
          labels: ${{ steps.meta_cross.outputs.labels }}
